from ip2geotools_locator.calculations.average import Average
from ip2geotools_locator.calculations.clusters import Clusters
from ip2geotools_locator.calculations.confidence_interval import ConfidenceInterval
from ip2geotools_locator.calculations.median import Median